---
- name: System upgrade.
  hosts: rancher
  become: yes

  tasks:
    - name: Run "apt-get update".
      apt:
        update_cache: yes

    - name: Run "apt-get upgrade".
      apt:
        upgrade: safe

- name: Synchronize time with NTP
  hosts: rancher
  become: yes

  tasks:
    - name: Install NTP daemon to keep the time in sync.
      package:
        name: chrony
        state: present

    - name: Enable and start NTP daemon.
      service:
        name: chronyd
        state: started
        enabled: yes

    - name: Make sure the hosts are synced with the NTP server.
      command: chronyd -q

- name: Disable swap.
  hosts: rancher
  become: yes

  tasks:
    - name: Check that the swap file exists.
      stat:
        path: /swap.img
      register: swap_stat_result

    - name: Deactivate the swap space.
      command: swapoff -v /swap.img
      when: swap_stat_result.stat.exists
    
    - name: Remove the swap file entry.
      lineinfile:
        path: /etc/fstab
        state: absent
        regexp: '^/swap.img'

    - name: Remove the actual swap file.
      file:
        dest: /swap.img
        state: absent
    
- name: Setup firewall.
  hosts: rancher
  become: yes

  tasks:
    - name: Open TCP port for traffic to Kubernetes API.
      iptables:
        action: append
        chain: INPUT
        jump: ACCEPT
        protocol: tcp
        destination_port: '6443'
        comment: Kubernetes API clients

- name: Load required kernel modules.
  hosts: rancher
  become: yes
  tags: kernel
  vars:
    kernel_modules:
      - br_netfilter
      - ip6_udp_tunnel
      - ip_set
      - ip_set_hash_ip
      - ip_set_hash_net
      - iptable_filter
      - iptable_nat
      - iptable_mangle
      - iptable_raw
      - nf_conntrack_netlink
      - nf_conntrack
      - nf_conntrack_ipv4
      - nf_defrag_ipv4
      - nf_nat
      - nf_nat_ipv4
      - nf_nat_masquerade_ipv4
      - nfnetlink
      - udp_tunnel
      - veth
      - vxlan
      - x_tables
      - xt_addrtype
      - xt_conntrack
      - xt_comment
      - xt_mark
      - xt_multiport
      - xt_nat
      - xt_recent
      - xt_set
      - xt_statistic
      - xt_tcpudp

  tasks:
    - name: Filter available kernel modules.
      shell: |
        if [ -z `find /lib/modules/$(uname -r) -type f -name "{{ item | quote }}"* | tr '     +++' '\n'` ]; then
          exit 1
        else
          echo "{{ item | quote }}"
          exit 0
        fi;
      ignore_errors: True
      changed_when: False
      loop: "{{ kernel_modules }}"
      register: filter_modules

    - name: Print result.
      debug:
        msg: "Item: {{ item.stdout }}"
      when: item.rc == 0
      loop: "{{ filter_modules.results }}"

#    - name: Load kernel modules for RKE
#      modprobe:
#        name: "{{ item }}"
#        state: present
#      with_items: "{{ kernel_modules }}"


