---
- name: System upgrade.
  hosts: rancher
  become: yes

  tasks:
    - name: Run "apt-get update".
      apt:
        update_cache: yes

    - name: Run "apt-get upgrade".
      apt:
        upgrade: safe

- name: Synchronize time with NTP
  hosts: rancher
  become: yes

  tasks:
    - name: Install NTP daemon to keep the time in sync.
      package:
        name: chrony
        state: present

    - name: Enable and start NTP daemon.
      service:
        name: chronyd
        state: started
        enabled: yes

    - name: Make sure the hosts are synced with the NTP server.
      command: chronyd -q

- name: Disable swap.
  hosts: rancher
  become: yes

  tasks:
    - name: Check that the swap file exists.
      stat:
        path: /swap.img
      register: swap_stat_result

    - name: Deactivate the swap space.
      command: swapoff -v /swap.img
      when: swap_stat_result.stat.exists
    
    - name: Remove the swap file entry.
      lineinfile:
        path: /etc/fstab
        state: absent
        regexp: '^/swap.img'

    - name: Remove the actual swap file.
      file:
        dest: /swap.img
        state: absent
    
- name: Setup firewall.
  hosts: rancher
  become: yes

  tasks:
    - name: Open TCP port for traffic to Kubernetes API.
      iptables:
        action: append
        chain: INPUT
        jump: ACCEPT
        protocol: tcp
        destination_port: '6443'
        comment: Kubernetes API clients



